@startditaa
                                    +---------------------
                                    : インストラクション領域
                                    |     関数はリンク後に
+---------------+                   |     インストラクション
|class Base     +---->+---------+   |     領域に配置される
+---------------+     |vtbl cPNK|   |                  
                      | for     |   |
                      | Base    +----->+--------------+
                      +---------+   |  |Base꞉꞉f()     |
                                    :  |  ... cGRE {d}|
                                    |  +--------------+
                                    |                  
                                    |  +--------------+
                                    |  |Base꞉꞉g()     |
                                    |  |  ... cBLU {d}|
                                    |  +--------------+
                                    |                  
                                    |  +--------------+
                                    |  |Base꞉꞉g(int)  |
                                    |  |  ... cBLU {d}|
                                    |  +--------------+
                                    |
+---------------+                   |
|class Derived  |                   |                  
|  ꞉public Base +---->+---------+   |                  
+---------------+     |vtbl cPNK|   |                  
                      | for     |   |
                      | Derived +----->+--------------+
                      +---------+   |  |Derived꞉꞉f()  |
                                    :  |  ... cGRE {d}|
                                    |  +--------------+
                                    |                  
                                    |  +--------------+
                                    |  |Derived꞉꞉g()  |
                                    |  |  ... cRED {d}|
                                    |  +--------------+
                                    |
+----+---------------------------=-+
|cGRE| override                    |
+----+---------------------------=-+
|cBLU| overload                    |
+----+---------------------------=-+
|cRED|not override and not overload|
+----+-----------------------------+
                            
@endditaa
